name = mobs_hs
title = Hell Sentinel
description = Adds the hell sentinel monster. Based on flux's mobs_hs.
author = kiedtl,rheo
license = LGPL-3.0-or-later
media_license = CC-BY-SA-3.0
version = 2024-02-22
min_minetest_version = 5.7.0
depends = default, fmod, futil, mobs
optional_depends = 3d_armor, armor_admin, armor_crystal, armor_monoid, pvpplus, rainbow_ore, shields, yl_cities, yl_events, yl_speak_up
release = 23646
